# Read the Docs configuration
# https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
