#! /bin/sh

###############################################################################
#
# Initializes all git submodules and augments the URL to bitbucket.org with
# your user name.  Clones all submodules.
#
###############################################################################

########################################
# Parameters
########################################

declare -r URL_PREFIX='https://'
declare -r URL_BASE_FET='bitbucket.org/ccgo/fet.git'
declare -r URL_BASE_MANGLL='bitbucket.org/ccgo/mangll.git'
declare -r URL_BASE_YMIR='bitbucket.org/ccgo/ymir.git'

########################################
# Functions
########################################

print_usage()
{
  echo "Usage: ./submodule_init [-b <BITBUCKET_USERNAME>]"
}

########################################
# Process options
########################################

# check option flags
while getopts ":hb:" opt; do
  case $opt in
    h) # help
      print_usage; exit 1
      ;;
    b) # bitbucket username
      bitbucket_user=$OPTARG
      ;;
    \?) # invalid option
      echo "Invalid option: -$OPTARG" >&2; exit 1
      ;;
    :) # option requires argument
      echo "Option -$OPTARG requires an argument" >&2; exit 1
      ;;
  esac
done

########################################
# Set up git submodules
########################################

# initialize submodules
git submodule init

# set user name in bitbucket URLs
if [ -n "${bitbucket_user:+SetNotNull}" ]; then # if variable is set and !null
  fet_url="${URL_PREFIX}${bitbucket_user}@${URL_BASE_FET}"
  mangll_url="${URL_PREFIX}${bitbucket_user}@${URL_BASE_MANGLL}"
  ymir_url="${URL_PREFIX}${bitbucket_user}@${URL_BASE_YMIR}"

  echo "Add bitbucket user name \"$bitbucket_user\" to submodule URLs:"
  echo "  fet:     $fet_url"
  echo "  mangll:  $mangll_url"
  echo "  ymir:    $ymir_url"

  git config --file .git/config submodule.fet.url $fet_url
  git config --file .git/config submodule.mangll.url $mangll_url
  git config --file .git/config submodule.ymir.url $ymir_url
fi

# get submodules' code
git submodule update
