#!/bin/bash

###############################################################################
#
# Configures the rhea code in the directory from which this script is called.
#
# Modules:
#   1) intel/17.0.4-74uvhji          4) StdEnv
#   2) intel-mpi/2017.3-dfphq6k      5) valgrind/3.13.0
#   3) intel-mkl/2017.3.196-v7uuj6z   
#
###############################################################################

THIS_ARCHITECTURE="Argonne LCRC, Intel compiler"
THIS_PETSC_DIR_DBG="/home/jrudi/build/perf/rhea_petsc" #TODO compile debug
THIS_PETSC_DIR_OPT="/home/jrudi/build/perf/rhea_petsc"
THIS_BLAS_LIBS="$THIS_PETSC_DIR_OPT/lib/libfblas.a"
THIS_LAPACK_LIBS="$THIS_PETSC_DIR_OPT/lib/libflapack.a"
THIS_VALGRIND_INC="/soft/bebop/valgrind/3.13.0/include/valgrind"

########################################
# Functions
########################################

function print_usage()
{
  echo "Usage: ./$(basename "$0") [-o]"
}

########################################
# Process options
########################################

# initialize parameters
is_opt=0
code_dir="$(dirname ${BASH_SOURCE[0]})/.."
build_dir="$(pwd)"

# check option flags
while getopts ":ho" opt; do
  case $opt in
    h) # help
      print_usage; exit 1
      ;;
    o) # optimized build
      is_opt=1
      ;;
    \?) # invalid option
      echo "Invalid option: -$OPTARG" >&2; exit 1
      ;;
    :) # option requires argument
      echo "Option -$OPTARG requires an argument" >&2; exit 1
      ;;
  esac
done

########################################
# Run configure
########################################

echo "========================================"
echo "Build rhea for $THIS_ARCHITECTURE"
echo "Code directory:  $code_dir"
echo "Build directory: $build_dir"
echo "Optimized build: $is_opt"
echo "========================================"

if [ 1 -le "$is_opt" ]; then
  # configure optimized build
  $code_dir/configure \
    FFLAGS="-g -O2 -fopenmp" \
    CFLAGS="-g -O2 -fopenmp -Wall -DYMIR_PETSC_CUSTOM -DFET_DISABLE_RESTRICT -DFET_DISABLE_DEBUG" \
  CXXFLAGS="-g -O2 -fopenmp -Wall" \
  CPPFLAGS="-I${THIS_VALGRIND_INC}" \
  --enable-mpi \
  --enable-openmp="-fopenmp" \
  --with-fet="$code_dir/fet" \
  --with-petsc="$THIS_PETSC_DIR_OPT" \
  BLAS_LIBS="$THIS_BLAS_LIBS" \
  LAPACK_LIBS="$THIS_LAPACK_LIBS"
else
  # configure development build
  $code_dir/configure \
    FFLAGS="-g -O0 -fopenmp" \
    CFLAGS="-g -O0 -fopenmp -Wall -DYMIR_PETSC_CUSTOM -DFET_DISABLE_RESTRICT" \
  CXXFLAGS="-g -O0 -fopenmp -Wall" \
  CPPFLAGS="-I${THIS_VALGRIND_INC}" \
  --enable-debug \
  --enable-mpi \
  --enable-openmp="-fopenmp" \
  --with-fet="$code_dir/fet" \
  --with-petsc="$THIS_PETSC_DIR_DBG" \
  BLAS_LIBS="$THIS_BLAS_LIBS" \
  LAPACK_LIBS="$THIS_LAPACK_LIBS"
fi
