#!/bin/bash

###############################################################################
#
# Configures the rhea code in the directory from which this script is called.
#
###############################################################################

THIS_ARCHITECTURE="TACC Frontera, Intel compiler"
THIS_PETSC_DIR_DBG="/home1/01501/johann/build/dev/rhea_petsc"
THIS_PETSC_DIR_OPT="/home1/01501/johann/build/perf/rhea_petsc"

########################################
# Functions
########################################

function print_usage()
{
  echo "Usage: ./$(basename "$0") [-o]"
}

########################################
# Process options
########################################

# initialize parameters
is_opt=0
script_dir="$(dirname ${BASH_SOURCE[0]})"
code_dir="$script_dir/.."
build_dir="$(pwd)"

# check option flags
while getopts ":ho" opt; do
  case $opt in
    h) # help
      print_usage; exit 1
      ;;
    o) # optimized build
      is_opt=1
      ;;
    \?) # invalid option
      echo "Invalid option: -$OPTARG" >&2; exit 1
      ;;
    :) # option requires argument
      echo "Option -$OPTARG requires an argument" >&2; exit 1
      ;;
  esac
done

########################################
# Setup environment
########################################

source $script_dir/setup_frontera.sh || exit

echo "========================================"
echo "Modules:"
module -t list 2>&1 | sort

THIS_BLAS_LIBS="-L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl"
THIS_VALGRIND_INC="$TACC_VALGRIND_INC"
OPENMP_FLAG="-qopenmp"

########################################
# Run configure
########################################

echo "========================================"
echo "Build rhea for $THIS_ARCHITECTURE"
echo "Code directory:  $code_dir"
echo "Build directory: $build_dir"
echo "Optimized build: $is_opt"
echo "========================================"

if [ 1 -le "$is_opt" ]; then
  # configure optimized build
  $code_dir/configure \
    FFLAGS="-g -O3 $OPENMP_FLAG" \
    CFLAGS="-g -O3 $OPENMP_FLAG -Wall -w2 -DYMIR_PETSC_CUSTOM -DFET_DISABLE_DEBUG" \
  CXXFLAGS="-g -O3 $OPENMP_FLAG -Wall -w2" \
  CPPFLAGS="-I${THIS_VALGRIND_INC}" \
  --enable-mpi \
  --enable-openmp="$OPENMP_FLAG" \
  --with-fet="$code_dir/fet" \
  --with-petsc="$THIS_PETSC_DIR_OPT" \
  BLAS_LIBS="$THIS_BLAS_LIBS"
else
  # configure development build
  $code_dir/configure \
    FFLAGS="-g -O0 $OPENMP_FLAG" \
    CFLAGS="-g -O0 $OPENMP_FLAG -Wall -w2 -DYMIR_PETSC_CUSTOM" \
  CXXFLAGS="-g -O0 $OPENMP_FLAG -Wall -w2" \
  CPPFLAGS="-I${THIS_VALGRIND_INC}" \
  --enable-debug \
  --enable-mpi \
  --enable-openmp="$OPENMP_FLAG" \
  --with-fet="$code_dir/fet" \
  --with-petsc="$THIS_PETSC_DIR_DBG" \
  BLAS_LIBS="$THIS_BLAS_LIBS"
fi

echo "========================================"
